<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [4]:
import numpy as np

In [5]:
#python lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
#numpy arrays
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [7]:
#dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
#each velue is paired w a key using :

### 1.2 Accessing data from a list (or array)

In [8]:
print(py_real_names[0])   #python is a zero-indexed language

Natasha Romanoff


In [11]:
print(py_super_names[1])  #forward indexing, need to know the size for this to work

Iron Man


In [12]:
print(py_super_names[-1])   #reverse indexing,-1 gives the last element of the list
                            #don't need to know the list size

Doctor Strange


### 1.3 Accessing data from a dictionary

In [15]:
print(superhero_info["Stephen Strange"])

Doctor Strange


In [16]:
#to access all keys and values:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [17]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [18]:
#using a 2D list instead of separated into 2
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW NumPy array

In [24]:
len(py_list_2d)    #to know how many elements there are in lists

10

In [25]:
len(np_array_2d)

10

In [26]:
np_array_2d.shape  #shape is not a function, it is a property or attribute of numpy array
#

(10, 2)

### 2.2 Arrays are fussy about type

In [27]:
py_list = [1, 1.5, 'A']
np.array(py_list)  
#numbers are converted into english ('') in arrays

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW NumPy array

In [29]:
py_list + 10   #won't work

TypeError: can only concatenate list (not "int") to list

In [30]:
np_array + 10
#array can add number like dis^

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [31]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [32]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [33]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [39]:
py_list*3   #cannot multiply, will j replicate same list 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [38]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [41]:
py_list**2   #won't work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [43]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [44]:
py_list==3   #works, but what is the qn???, applies it to the whole list

False

In [45]:
py_list>3    #won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [46]:
np_array == 3

array([False, False,  True, False, False])

In [47]:
np_array>3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [49]:
sum(py_list)  #sum() is a base python function

15

In [50]:
max(py_list)  #max() is a base python function

5

In [51]:
min(py_list)  #min() is a base python function

1

In [52]:
py_list.sum() #won't work!

AttributeError: 'list' object has no attribute 'sum'

In [53]:
np_array.sum()

15

In [54]:
np_array.mean()

3.0

In [55]:
np_array.max()

5

In [56]:
np_array.min()

1

## Exercise 1 :  Total recall?

In [57]:
#numpy arrays can only be added tgt if they have the same array size

2 similarities between lists and arrays:
1. order of the items stored matters
1. both need two lists/arrays to store the same data, vs dictionary can hold multiple datasets in one dictionary

2 differences between lists and arrays:
1. arrays prefer using a single data type, while lists can have more than one data type (need to typecast for arrays)
1. multiplying lists by a number makes the list grow, but for arrays, the elements within the array will be multiplied

what is a dictionary?
it is a way of storing datasets, by pairing a value to a key. it makes use of lesser functions than lists or arrays.

## Exercise 2 :  Index me

In [10]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [6]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()     
print(superhero_info['Tony Stark'])
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()     
print(superhero_info['Natasha Romanoff'])
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()     
print(superhero_info['Stephen Strange'])

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [48]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 
count = numbers.count(1)
print(count)

9
