<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_arrayb

### 1.2 Subsetting by masking (Arrays only)

In [2]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [3]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
np_array[np_array > 3]   #summarised

In [4]:
np_array[~(np_array > 3)]    # '~' means 'NOT'

array([1, 2, 3])

In [5]:
np_array[(np_array > 3) & (np_array < 8)]   # '&' means 'AND'

array([4, 5, 6, 7])

In [6]:
np_array[(np_array < 3) | (np_array > 8)]   # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [7]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [8]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [9]:
py_list_2d[:3]   #index 0 to 3

[[1, 'A'], [2, 'B'], [3, 'C']]

In [10]:
py_list_2d[:3][0]   
#does NOT give first elements (ie. [1,2,3]) of all the sub-lists up to index 2

[1, 'A']

In [11]:
py_list_2d[3:6][0]  #index 3 to 5, first element of this range

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [13]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [14]:
np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [15]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)
#DIFFERENT FOR ARRAYS
#uses single [] vs lists

'4'

In [16]:
np_array_2d[:3]     #index 0 to 3

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [17]:
np_array_2d[:3, 0]   #index 0 to 3, first element of each sublist!!

array(['1', '2', '3'], dtype='<U21')

In [18]:
np_array_2d[3:6, 0]     #index 3 to 5, first element of each sublist

array(['4', '5', '6'], dtype='<U21')

In [21]:
np_array_2d[:, 0]
#to give everything, first element of each sublist!

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

### 1.5 Growing lists

In [22]:
x=[1]*10
x               # don't need type print()
#growing py list

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [23]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [24]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
#same as above

[1, 2, 3, 4]

In [25]:
x=[1]
x+= [2, 3, 4]
x
#appending multiple elements in one go

[1, 2, 3, 4]

In [26]:
x=[1]
x= [2, 3, 4] + x
x
#in the case of pre-pending stuff

[2, 3, 4, 1]

In [27]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [28]:
a=(1, 2, 3)     # Define tuple

In [29]:
print(a[0])    # Access data

1


In [30]:
# The following will NOT work, cannot append?
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [31]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [32]:
#correct way:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

subsetting - selecting a subset of data (one element, multiple elements, etc) from a defined data set
indexing - getting one element from a dataset
slicing - getting a range of elements from a dataset
masking - shows specific desired values by asking questions and getting a true or false answer for each value

## Exercise 2 :  Show me the ‘odd’ letters

In [60]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_new = np_array_2d[:, 0].astype(int)
np_array_new%2
my_mask =np_array_new%2 == 1   #to get the odd numbers!
print(my_mask)
np_array[my_mask]
np_array_2d[my_mask, 1]

[ True  True False False  True  True False False False  True]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')